[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
include_paths = ["node_modules"]
optimizer = true
optimizer_runs = 1000000
verbosity = 2

[fuzz]
runs = 4096

[profile.ci]
verbosity = 4